// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxVsqWrgSxMuz5v-QVMT7HU8malYyXTtw',
    appId: '1:241215668669:web:192058707646bd97b2d2d4',
    messagingSenderId: '241215668669',
    projectId: 'reimagine-7f6da',
    authDomain: 'reimagine-7f6da.firebaseapp.com',
    storageBucket: 'reimagine-7f6da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAllBfaIo3pi0CASATSTB9s244SD6uJxXU',
    appId: '1:241215668669:android:e368bca88f0aa389b2d2d4',
    messagingSenderId: '241215668669',
    projectId: 'reimagine-7f6da',
    storageBucket: 'reimagine-7f6da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsY617lYSYlMvxtbx5XBMbBAqedQLdAUI',
    appId: '1:241215668669:ios:b04a51b5ad49f897b2d2d4',
    messagingSenderId: '241215668669',
    projectId: 'reimagine-7f6da',
    storageBucket: 'reimagine-7f6da.firebasestorage.app',
    iosBundleId: 'com.example.reimagine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsY617lYSYlMvxtbx5XBMbBAqedQLdAUI',
    appId: '1:241215668669:ios:b04a51b5ad49f897b2d2d4',
    messagingSenderId: '241215668669',
    projectId: 'reimagine-7f6da',
    storageBucket: 'reimagine-7f6da.firebasestorage.app',
    iosBundleId: 'com.example.reimagine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxVsqWrgSxMuz5v-QVMT7HU8malYyXTtw',
    appId: '1:241215668669:web:a6fb1ca43592b85db2d2d4',
    messagingSenderId: '241215668669',
    projectId: 'reimagine-7f6da',
    authDomain: 'reimagine-7f6da.firebaseapp.com',
    storageBucket: 'reimagine-7f6da.firebasestorage.app',
  );

}