// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_v67O-IP42-pp50gAPvP7yN_o0tVHpO8',
    appId: '1:1077602217163:web:636accd332c6a9d0b0bf4e',
    messagingSenderId: '1077602217163',
    projectId: 'reimagine-fddda',
    authDomain: 'reimagine-fddda.firebaseapp.com',
    storageBucket: 'reimagine-fddda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8TjfdsH6lN5kcQSY_JnyskVBAMyro4nA',
    appId: '1:1077602217163:android:24fef53b2a82c576b0bf4e',
    messagingSenderId: '1077602217163',
    projectId: 'reimagine-fddda',
    storageBucket: 'reimagine-fddda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBA8CR-7N6RmUHKYky3eKH3peBU9NckTI',
    appId: '1:1077602217163:ios:3c98756afcdbe017b0bf4e',
    messagingSenderId: '1077602217163',
    projectId: 'reimagine-fddda',
    storageBucket: 'reimagine-fddda.appspot.com',
    iosBundleId: 'com.example.reimagine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBA8CR-7N6RmUHKYky3eKH3peBU9NckTI',
    appId: '1:1077602217163:ios:3c98756afcdbe017b0bf4e',
    messagingSenderId: '1077602217163',
    projectId: 'reimagine-fddda',
    storageBucket: 'reimagine-fddda.appspot.com',
    iosBundleId: 'com.example.reimagine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_v67O-IP42-pp50gAPvP7yN_o0tVHpO8',
    appId: '1:1077602217163:web:04cd9cf15949d536b0bf4e',
    messagingSenderId: '1077602217163',
    projectId: 'reimagine-fddda',
    authDomain: 'reimagine-fddda.firebaseapp.com',
    storageBucket: 'reimagine-fddda.appspot.com',
  );
}
